[package]
name = "func_man"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28.1"
instant = "0.1.13"
log = "0.4.22"
femtovg = "0.9.1"
glutin = "0.30.0"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.2"
